const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const services={modeling:{name:'3D‑моделирование',base:2500,time:'2–4 раб. дня'},scan:{name:'3D‑сканирование',base:2500,time:'1–3 раб. дня'},print:{name:'3D‑печать',base:700,time:'1–4 раб. дня'},reverse:{name:'Реверс‑инжиниринг',base:8000,time:'3–7 раб. дней'},design:{name:'Промышленный дизайн',base:50000,time:'10–20 раб. дней'},xr:{name:'AR / VR / 3D‑контент',base:50000,time:'10–25 раб. дней'}};
const form=$('#estimateForm'),service=$('#service'),complexity=$('#complexity'),urgency=$('#urgency'),qty=$('#qty'),desc=$('#description'),nameEl=$('#name'),contact=$('#contact'),consent=$('#consent'),dynamic=$('#dynamicField');
let toastTimer;
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}
function money(n){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n))+' ₽'}
function dynamicField(){const v=service.value; if(v==='print') dynamic.innerHTML='<label for="extra">Технология</label><select id="extra"><option value="1">FDM</option><option value="2.2">SLA / фотополимер</option><option value="3">Спец. технология</option></select>'; else if(v==='scan') dynamic.innerHTML='<label for="extra">Размер объекта</label><select id="extra"><option value="1">Малый</option><option value="1.5">Средний</option><option value="2.2">Крупный</option></select>'; else dynamic.innerHTML='<label for="extra">Формат результата</label><select id="extra"><option value="1">Стандартный</option><option value="1.15">+ документация</option></select>'; $('#extra').addEventListener('change',calc)}
function score(){let s=20;if(desc.value.trim().length>40)s+=30;if(nameEl.value.trim())s+=15;if(contact.value.trim())s+=25;if(consent.checked)s+=10;return Math.min(100,s)}
function calc(){const cfg=services[service.value];const extra=Number($('#extra')?.value||1);const q=Math.max(1,Number(qty.value)||1);let base=cfg.base*Number(complexity.value)*Number(urgency.value)*extra; if(service.value==='print')base*=Math.max(1,Math.pow(q,.82));else if(q>1)base*=1+(q-1)*.35;const lo=Math.round(base/100)*100,hi=Math.round(base*1.3/100)*100;$('#price').textContent='от '+money(lo);$('#range').textContent=`Ориентир: ${money(lo)}–${money(hi)}`;$('#summaryService').textContent=cfg.name;$('#summaryTime').textContent=urgency.value==='1.5'?'приоритетно · '+cfg.time:cfg.time;const sc=score();$('#briefScore').textContent=sc+'%';$('#progressBar').style.width=sc+'%';$('#resultNote').textContent=sc>=80?'Бриф выглядит достаточно полным для первичной технической проверки.':'Добавьте описание и контакт — расчёт станет полезнее для технической проверки.';return{cfg,lo,hi,sc,q}}
function requestText(){const r=calc();return `STEP_3D — предварительная заявка\n\nУслуга: ${r.cfg.name}\nСложность: ${complexity.options[complexity.selectedIndex].text}\nСрок: ${urgency.options[urgency.selectedIndex].text}\nКоличество: ${r.q}\nОриентир стоимости: ${money(r.lo)}–${money(r.hi)}\nОриентир срока: ${$('#summaryTime').textContent}\nГотовность брифа: ${r.sc}%\n\nОписание задачи:\n${desc.value.trim()||'—'}\n\nЗаказчик: ${nameEl.value.trim()||'—'}\nКонтакт: ${contact.value.trim()||'—'}\n\nРасчёт предварительный и требует технической проверки.`}
function goEstimate(v){service.value=v;dynamicField();calc();$('#estimate').scrollIntoView({behavior:'smooth',block:'start'})}
$$('.service').forEach(c=>c.querySelector('button').addEventListener('click',()=>goEstimate(c.dataset.service)));
$$('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const p=b.dataset.preset;if(p==='idea'){service.value='design';desc.value='Есть идея изделия. Нужны концепция, 3D‑модель и прототип.'}if(p==='drawing'){service.value='modeling';desc.value='Есть чертёж или эскиз. Нужна корректная 3D‑модель для дальнейшего производства.'}if(p==='model'){service.value='print';desc.value='Есть готовый 3D‑файл. Нужно проверить технологичность и изготовить изделие.'}if(p==='object'){service.value='reverse';desc.value='Есть физическая деталь. Нужно оцифровать геометрию и восстановить CAD‑модель.'}dynamicField();calc();$('#estimate').scrollIntoView({behavior:'smooth'})}));
[service,complexity,urgency,qty,desc,nameEl,contact,consent].forEach(el=>el.addEventListener(el.type==='checkbox'?'change':'input',calc));service.addEventListener('change',()=>{dynamicField();calc()});desc.addEventListener('input',()=>$('#descCount').textContent=desc.value.length+'/500');
$('#sendBtn').addEventListener('click',()=>{if(!contact.value.trim()){toast('Укажите контакт для ответа');contact.focus();return}if(!consent.checked){toast('Нужно подтвердить согласие');consent.focus();return}$('#requestText').value=requestText();$('#requestDialog').showModal()});
$('#copyBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText(requestText());toast('Расчёт скопирован')});$('#dialogCopy').addEventListener('click',async()=>{await navigator.clipboard.writeText($('#requestText').value);toast('Заявка скопирована')});$('#closeDialog').addEventListener('click',()=>$('#requestDialog').close());
const menu=$('#menuBtn'),nav=$('#nav');menu.addEventListener('click',()=>{const o=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!o));nav.classList.toggle('open',!o)});$$('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
const theme=$('#themeBtn');const saved=localStorage.getItem('step3d-theme');if(saved==='dark')document.body.classList.add('dark');theme.addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('step3d-theme',document.body.classList.contains('dark')?'dark':'light')});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});$$('.reveal').forEach(e=>io.observe(e));const sections=$$('main section[id]'),navLinks=$$('#nav a');const sio=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}}),{rootMargin:'-30% 0px -60%'});sections.forEach(s=>sio.observe(s));addEventListener('scroll',()=>$('.topbar').classList.toggle('scrolled',scrollY>20),{passive:true});
dynamicField();calc();
